### ISSUE TITLE
Windows 10: NoAvailablePixelFormat.

### ISSUE THREAD

**Issue by Kesanov** [sixtyfpsui/sixtyfps#481]
I tried to run the sliding_puzzle example and received this runtime error:
```    
Finished dev [unoptimized + debuginfo] target(s) in 0.55s
     Running `target\debug\Sixty.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', E:\Users\Me\.cargo\registry\src\github.com-1ecc6299db9ec823\sixtyfps-rendering-backend-gl-0.1.2\lib.rs:179:88
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:515
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\panicking.rs:92
   2: core::result::unwrap_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\result.rs:1355
   3: enum$<core::result::Result<glutin::windowed::ContextWrapper<enum$<glutin::context::NotCurrent>, winit::window::Window>, enum$<glutin::CreationError>>>::unwrap<glutin::windowed::ContextWrapper<enum$<glutin::context::NotCurrent>, winit::window::Window>,enum
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\result.rs:1037
   4: sixtyfps_rendering_backend_gl::{{impl}}::new_context_and_renderer::{{closure}}
             at E:\Users\Me\.cargo\registry\src\github.com-1ecc6299db9ec823\sixtyfps-rendering-backend-gl-0.1.2\lib.rs:179
   5: sixtyfps_rendering_backend_gl::event_loop::with_window_target::{{closure}}<glutin::windowed::ContextWrapper<enum$<glutin::context::NotCurrent>, winit::window::Window>,closure-0>
             at E:\Users\Me\.cargo\registry\src\github.com-1ecc6299db9ec823\sixtyfps-rendering-backend-gl-0.1.2\event_loop.rs:128
   6: std::thread::local::LocalKey<core::cell::RefCell<enum$<core::option::Option<sixtyfps_rendering_backend_gl::event_loop::NotRunningEventLoop>, 0, 3, Some>>>::try_with<core::cell::RefCell<enum$<core::option::Option<sixtyfps_rendering_backend_gl::event_loop::
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\std\src\thread\local.rs:400
   7: std::thread::local::LocalKey<core::cell::RefCell<enum$<core::option::Option<sixtyfps_rendering_backend_gl::event_loop::NotRunningEventLoop>, 0, 3, Some>>>::with<core::cell::RefCell<enum$<core::option::Option<sixtyfps_rendering_backend_gl::event_loop::NotR
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\std\src\thread\local.rs:376
   8: sixtyfps_rendering_backend_gl::event_loop::with_window_target<glutin::windowed::ContextWrapper<enum$<glutin::context::NotCurrent>, winit::window::Window>,closure-0>
             at E:\Users\Me\.cargo\registry\src\github.com-1ecc6299db9ec823\sixtyfps-rendering-backend-gl-0.1.2\event_loop.rs:124
   9: sixtyfps_rendering_backend_gl::OpenGLContext::new_context_and_renderer
             at E:\Users\Me\.cargo\registry\src\github.com-1ecc6299db9ec823\sixtyfps-rendering-backend-gl-0.1.2\lib.rs:172
  10: sixtyfps_rendering_backend_gl::graphics_window::GraphicsWindow::map_window
             at E:\Users\Me\.cargo\registry\src\github.com-1ecc6299db9ec823\sixtyfps-rendering-backend-gl-0.1.2\graphics_window.rs:133
  11: sixtyfps_rendering_backend_gl::graphics_window::{{impl}}::show
             at E:\Users\Me\.cargo\registry\src\github.com-1ecc6299db9ec823\sixtyfps-rendering-backend-gl-0.1.2\graphics_window.rs:499
  12: sixtyfps_corelib::window::Window::show
             at E:\Users\Me\.cargo\registry\src\github.com-1ecc6299db9ec823\sixtyfps-corelib-0.1.2\window.rs:404
  13: sixtyfps_corelib::window::api::Window::show
             at E:\Users\Me\.cargo\registry\src\github.com-1ecc6299db9ec823\sixtyfps-corelib-0.1.2\window.rs:541
  14: Sixty::sixtyfps_generated_MainWindow::{{impl}}::show
             at .\target\debug\build\Sixty-4ecbde4bd972ede7\out\puzzle.rs:2085
  15: Sixty::sixtyfps_generated_MainWindow::{{impl}}::run
             at .\target\debug\build\Sixty-4ecbde4bd972ede7\out\puzzle.rs:2080
  16: Sixty::main
             at .\src\main.rs:227
  17: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\Sixty.exe` (exit code: 101)
```

**Comment by tronical** [comment]
Thanks for the report! By any chance, are you running Windows inside a virtual machine?

**Comment by tronical** [comment]
Also, in this environment, could you try something for me? Please clone the sixtyfps GitHub repo, go into `sixtyfps_runtime/rendering_backends/gl/lib.rs` and search for the two lines

```rust
                #[cfg(target_os = "windows")]
                let builder = builder.with_srgb(false);
```

If you comment those out (or delete them), and then run the slide puzzle demo in `examples/slide_puzzle` with `cargo run`, does it work then?

**Comment by Kesanov** [comment]
Nope. However, I use integrated graphics Ryzen 3 2200G.

**Comment by Kesanov** [comment]
Commenting out the lines solved the problem.

**Comment by tronical** [comment]
Thank you for checking. Then I think I'll make a change to narrow down the "with_srgb" workaround (for basically the same problem, but inverted) to just the VMware GL driver.

**Comment by ogoffart** [comment]
Maybe we can do that automatically if we get the `NoAvailablePixelFormat` error in  sixtyfps-rendering-backend-gl-0.1.2\lib.rs:179

And i think we should not unwrap this error probably but show a nicer error message in case of error.

**Comment by tronical** [comment]
Yss, that's exactly what I was thinking. Try the without srgb, fall back to glutin default and otherwise use expect().

**Comment by tronical** [comment]
I've made a merge request that tries the "old" way first and then falls back to the default. @Kesanov , in your git clone of SixtyFPS, could you try checking out the "simon/opengl-context-dance" branch (after git fetch) and see if then the slide puzzle works out of the box for you? (without any local changes).

I verified that the merge request fixes the original issue I see in my VMware installation.

**Comment by Kesanov** [comment]
Works on my end.

**Comment by tronical** [comment]
Thanks for checking :)
