### ISSUE TITLE
Crash when running the gallery example on Qt backend

### ISSUE THREAD

**Issue by hch12907** [sixtyfpsui/sixtyfps#775]
The crash happens when I switch to another tab. Upon clicking on either `ListView`, `TextEdit`, or `About`, the program abruptly exits and a stack trace is printed (see below).

SixtyFPS version: ec26714
Qt version: 5.15.2 (MSVC 2019 x64)
OS: Windows 10 x64

```
thread 'main' panicked at 'Constant property being changed', sixtyfps_runtime\corelib\properties.rs:588:13
stack backtrace:
   0: std::panicking::begin_panic<str>
             at /rustc/91b931926fd49fc97d1e39f2b8206abf1d77ce7d\library\std\src\panicking.rs:521
   1: sixtyfps_corelib::properties::PropertyHandle::mark_dirty
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\properties.rs:588
   2: sixtyfps_corelib::properties::Property<bool>::set<bool>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\properties.rs:786
   3: sixtyfps_rendering_backend_qt::qt_widgets::tabwidget::impl$2::input_event
             at C:\...\sixtyfps\sixtyfps_runtime\rendering_backends\qt\qt_widgets\tabwidget.rs:393
   4: sixtyfps_rendering_backend_qt::qt_widgets::tabwidget::NativeTabVTable::input_event<sixtyfps_rendering_backend_qt::qt_widgets::tabwidget::NativeTab>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\items.rs:86
   5: sixtyfps_corelib::items::Item_vtable_mod::ItemTO::input_event
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\items.rs:86
   6: sixtyfps_corelib::input::process_mouse_input::closure$1
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\input.rs:352
   7: sixtyfps_corelib::item_tree::visit_internal::closure$0<tuple$<euclid::vector::Vector2D<f32,euclid::UnknownUnit>,alloc::vec::Vec<tuple$<sixtyfps_corelib::items::ItemWeak,enum$<sixtyfps_corelib::input::InputEventFilterResult> >,alloc::alloc::Global> >,enum$
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:206
   8: sixtyfps_corelib::item_tree::impl$2::visit_item<sixtyfps_corelib::item_tree::visit_internal::closure$0>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:126
   9: sixtyfps_corelib::item_tree::ItemVisitor_vtable_mod::impl$0::new::visit_item<sixtyfps_corelib::item_tree::visit_internal::closure$0>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:97
  10: sixtyfps_corelib::item_tree::ItemVisitor_vtable_mod::ItemVisitorTO::visit_item
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:97
  11: sixtyfps_corelib::item_tree::visit_item_tree::closure$0<gallery::sixtyfps_generated_App::InnerApp,sixtyfps_corelib::item_tree::VisitChildrenResult (*)(core::pin::Pin<ref$<gallery::sixtyfps_generated_App::InnerApp> >,enum$<sixtyfps_corelib::item_tree::Trav
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:245
  12: sixtyfps_corelib::item_tree::visit_item_tree<gallery::sixtyfps_generated_App::InnerApp,sixtyfps_corelib::item_tree::VisitChildrenResult (*)(core::pin::Pin<ref$<gallery::sixtyfps_generated_App::InnerApp> >,enum$<sixtyfps_corelib::item_tree::TraversalOrder>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:268
  13: gallery::sixtyfps_generated_App::impl$19::visit_children_item
             at C:\...\sixtyfps\target\debug\build\gallery-f8ae83e43d34991b\out\gallery.rs:1910
  14: gallery::sixtyfps_generated_App::impl$20::item_tree::VT::visit_children_item<gallery::sixtyfps_generated_App::InnerApp>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\component.rs:15
  15: sixtyfps_corelib::component::Component_vtable_mod::ComponentTO::visit_children_item
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\component.rs:15
  16: sixtyfps_corelib::item_tree::visit_internal<tuple$<euclid::vector::Vector2D<f32,euclid::UnknownUnit>,alloc::vec::Vec<tuple$<sixtyfps_corelib::items::ItemWeak,enum$<sixtyfps_corelib::input::InputEventFilterResult> >,alloc::alloc::Global> >,enum$<core::opti
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:217
  17: sixtyfps_corelib::item_tree::visit_internal::closure$0<tuple$<euclid::vector::Vector2D<f32,euclid::UnknownUnit>,alloc::vec::Vec<tuple$<sixtyfps_corelib::items::ItemWeak,enum$<sixtyfps_corelib::input::InputEventFilterResult> >,alloc::alloc::Global> >,enum$
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:205
  18: sixtyfps_corelib::item_tree::impl$2::visit_item<sixtyfps_corelib::item_tree::visit_internal::closure$0>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:126
  19: sixtyfps_corelib::item_tree::ItemVisitor_vtable_mod::impl$0::new::visit_item<sixtyfps_corelib::item_tree::visit_internal::closure$0>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:97
  20: sixtyfps_corelib::item_tree::ItemVisitor_vtable_mod::ItemVisitorTO::visit_item
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:97
  21: sixtyfps_corelib::item_tree::visit_item_tree::closure$0<gallery::sixtyfps_generated_App::InnerApp,sixtyfps_corelib::item_tree::VisitChildrenResult (*)(core::pin::Pin<ref$<gallery::sixtyfps_generated_App::InnerApp> >,enum$<sixtyfps_corelib::item_tree::Trav
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:245
  22: sixtyfps_corelib::item_tree::visit_item_tree<gallery::sixtyfps_generated_App::InnerApp,sixtyfps_corelib::item_tree::VisitChildrenResult (*)(core::pin::Pin<ref$<gallery::sixtyfps_generated_App::InnerApp> >,enum$<sixtyfps_corelib::item_tree::TraversalOrder>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:268
  23: gallery::sixtyfps_generated_App::impl$19::visit_children_item
             at C:\...\sixtyfps\target\debug\build\gallery-f8ae83e43d34991b\out\gallery.rs:1910
  24: gallery::sixtyfps_generated_App::impl$20::item_tree::VT::visit_children_item<gallery::sixtyfps_generated_App::InnerApp>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\component.rs:15
  25: sixtyfps_corelib::component::Component_vtable_mod::ComponentTO::visit_children_item
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\component.rs:15
  26: sixtyfps_corelib::item_tree::visit_internal<tuple$<euclid::vector::Vector2D<f32,euclid::UnknownUnit>,alloc::vec::Vec<tuple$<sixtyfps_corelib::items::ItemWeak,enum$<sixtyfps_corelib::input::InputEventFilterResult> >,alloc::alloc::Global> >,enum$<core::opti
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:217
  27: sixtyfps_corelib::item_tree::visit_internal::closure$0<tuple$<euclid::vector::Vector2D<f32,euclid::UnknownUnit>,alloc::vec::Vec<tuple$<sixtyfps_corelib::items::ItemWeak,enum$<sixtyfps_corelib::input::InputEventFilterResult> >,alloc::alloc::Global> >,enum$
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:205
  28: sixtyfps_corelib::item_tree::impl$2::visit_item<sixtyfps_corelib::item_tree::visit_internal::closure$0>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:126
  29: sixtyfps_corelib::item_tree::ItemVisitor_vtable_mod::impl$0::new::visit_item<sixtyfps_corelib::item_tree::visit_internal::closure$0>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:97
  30: sixtyfps_corelib::item_tree::ItemVisitor_vtable_mod::ItemVisitorTO::visit_item
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:97
  31: sixtyfps_corelib::item_tree::visit_item_tree::closure$0<gallery::sixtyfps_generated_App::InnerApp,sixtyfps_corelib::item_tree::VisitChildrenResult (*)(core::pin::Pin<ref$<gallery::sixtyfps_generated_App::InnerApp> >,enum$<sixtyfps_corelib::item_tree::Trav
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:245
  32: sixtyfps_corelib::item_tree::visit_item_tree<gallery::sixtyfps_generated_App::InnerApp,sixtyfps_corelib::item_tree::VisitChildrenResult (*)(core::pin::Pin<ref$<gallery::sixtyfps_generated_App::InnerApp> >,enum$<sixtyfps_corelib::item_tree::TraversalOrder>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:268
  33: gallery::sixtyfps_generated_App::impl$19::visit_children_item
             at C:\...\sixtyfps\target\debug\build\gallery-f8ae83e43d34991b\out\gallery.rs:1910
  34: gallery::sixtyfps_generated_App::impl$20::item_tree::VT::visit_children_item<gallery::sixtyfps_generated_App::InnerApp>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\component.rs:15
  35: sixtyfps_corelib::component::Component_vtable_mod::ComponentTO::visit_children_item
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\component.rs:15
  36: sixtyfps_corelib::item_tree::visit_internal<tuple$<euclid::vector::Vector2D<f32,euclid::UnknownUnit>,alloc::vec::Vec<tuple$<sixtyfps_corelib::items::ItemWeak,enum$<sixtyfps_corelib::input::InputEventFilterResult> >,alloc::alloc::Global> >,enum$<core::opti
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:217
  37: sixtyfps_corelib::item_tree::visit_internal::closure$0<tuple$<euclid::vector::Vector2D<f32,euclid::UnknownUnit>,alloc::vec::Vec<tuple$<sixtyfps_corelib::items::ItemWeak,enum$<sixtyfps_corelib::input::InputEventFilterResult> >,alloc::alloc::Global> >,enum$
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:205
  38: sixtyfps_corelib::item_tree::impl$2::visit_item<sixtyfps_corelib::item_tree::visit_internal::closure$0>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:126
  39: sixtyfps_corelib::item_tree::ItemVisitor_vtable_mod::impl$0::new::visit_item<sixtyfps_corelib::item_tree::visit_internal::closure$0>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:97
  40: sixtyfps_corelib::item_tree::ItemVisitor_vtable_mod::ItemVisitorTO::visit_item
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:97
  41: sixtyfps_corelib::item_tree::visit_item_tree::closure$0<gallery::sixtyfps_generated_App::InnerApp,sixtyfps_corelib::item_tree::VisitChildrenResult (*)(core::pin::Pin<ref$<gallery::sixtyfps_generated_App::InnerApp> >,enum$<sixtyfps_corelib::item_tree::Trav
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:245
  42: sixtyfps_corelib::item_tree::visit_item_tree<gallery::sixtyfps_generated_App::InnerApp,sixtyfps_corelib::item_tree::VisitChildrenResult (*)(core::pin::Pin<ref$<gallery::sixtyfps_generated_App::InnerApp> >,enum$<sixtyfps_corelib::item_tree::TraversalOrder>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:259
  43: gallery::sixtyfps_generated_App::impl$19::visit_children_item
             at C:\...\sixtyfps\target\debug\build\gallery-f8ae83e43d34991b\out\gallery.rs:1910
  44: gallery::sixtyfps_generated_App::impl$20::item_tree::VT::visit_children_item<gallery::sixtyfps_generated_App::InnerApp>
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\component.rs:15
  45: sixtyfps_corelib::component::Component_vtable_mod::ComponentTO::visit_children_item
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\component.rs:15
  46: sixtyfps_corelib::item_tree::visit_internal<tuple$<euclid::vector::Vector2D<f32,euclid::UnknownUnit>,alloc::vec::Vec<tuple$<sixtyfps_corelib::items::ItemWeak,enum$<sixtyfps_corelib::input::InputEventFilterResult> >,alloc::alloc::Global> >,enum$<core::opti
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:217
  47: sixtyfps_corelib::item_tree::visit_items_with_post_visit<tuple$<euclid::vector::Vector2D<f32,euclid::UnknownUnit>,alloc::vec::Vec<tuple$<sixtyfps_corelib::items::ItemWeak,enum$<sixtyfps_corelib::input::InputEventFilterResult> >,alloc::alloc::Global> >,enu
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\item_tree.rs:177
  48: sixtyfps_corelib::input::process_mouse_input
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\input.rs:299
  49: sixtyfps_corelib::window::Window::process_mouse_input
             at C:\...\sixtyfps\sixtyfps_runtime\corelib\window.rs:270
  50: sixtyfps_rendering_backend_qt::qt_window::QtWindow::mouse_event
             at C:\...\sixtyfps\sixtyfps_runtime\rendering_backends\qt\qt_window.rs:1170
  51: sixtyfps_rendering_backend_qt::qt_window::SFPS_mousePressEvent::closure$0
             at C:\...\sixtyfps\sixtyfps_runtime\rendering_backends\qt\qt_window.rs:103
  52: sixtyfps_rendering_backend_qt::qt_window::SFPS_mousePressEvent
             at C:\Users\hch12907\.cargo\registry\src\github.com-1ecc6299db9ec823\cpp-0.5.6\src\lib.rs:254
  53: SixtyFPSWidget::mousePressEvent
             at C:\...\sixtyfps\sixtyfps_runtime\rendering_backends\qt\qt_window.rs:100
  54: QStyleAnimation::frameRate
  55: QStyleAnimation::frameRate
  56: QStyleAnimation::frameRate
  57: QTextStream::realNumberPrecision
  58: QTextStream::realNumberPrecision
  59: QStyleAnimation::frameRate
  60: QStyleAnimation::frameRate
  61: QStyleAnimation::frameRate
  62: QStyleAnimation::frameRate
  63: QStyleAnimation::frameRate
  64: QTextStream::realNumberPrecision
  65: QTextStream::realNumberPrecision
  66: QOpenGLFunctions_4_3_Compatibility::glLightModeli
  67: QOpenGLFunctions_4_3_Compatibility::glLightModeli
  68: QOpenGLFunctions_4_3_Compatibility::glLightModeli
  69: qt_plugin_instance
  70: QTextStream::realNumberPrecision
  71: qt_plugin_instance
  72: QTextStream::realNumberPrecision
  73: QTextStream::realNumberPrecision
  74: QTextStream::realNumberPrecision
  75: QOpenGLFunctions_4_3_Compatibility::glLightModeli
  76: QStyleAnimation::frameRate
  77: __cpp_closure_1553422644876351010
             at C:\...\sixtyfps\sixtyfps_runtime\rendering_backends\qt\lib.rs:139
  78: sixtyfps_rendering_backend_qt::impl$0::run_event_loop
             at C:\...\sixtyfps\sixtyfps_runtime\rendering_backends\qt\lib.rs:136
  79: sixtyfps::run_event_loop
             at C:\...\sixtyfps\api\sixtyfps-rs\lib.rs:425
  80: gallery::sixtyfps_generated_App::impl$22::run
             at C:\...\sixtyfps\target\debug\build\gallery-f8ae83e43d34991b\out\gallery.rs:10756
  81: gallery::main
             at .\main.rs:19
  82: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/91b931926fd49fc97d1e39f2b8206abf1d77ce7d\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `C:\...\sixtyfps\target\debug\gallery.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by ogoffart** [comment]
Thanks for testing and reporting the bug!

This is now fixed in master.
